print("Welcome to the Band Generator")
print("What is the name of the city you grew up in?")
city =  input()
print("What's your pet's name?")
pet = input()
print ("Your band name could be", city, pet)
